version: 1.2.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - ps: nuget restore
image: Visual Studio 2017
configuration: Release
build:
  parallel: true 
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.6.519\\tools\\OpenCover.Console.exe\" -register:user -target:\"%xunit20%\\xunit.console.x86.exe\" -targetargs:\"Grumpy.MessageQueue.UnitTests\\bin\\Release\\Grumpy.MessageQueue.UnitTests.dll Grumpy.MessageQueue.Msmq.UnitTests\\bin\\Release\\Grumpy.MessageQueue.Msmq.UnitTests.dll Grumpy.MessageQueue.TestTools.UnitTests\\bin\\Release\\Grumpy.MessageQueue.TestTools.UnitTests.dll -noshadow\" -output:\"coverage.xml\" -filter:\"+[Grumpy.MessageQueue*]* -[Grumpy.MessageQueue.UnitTests*|Grumpy.MessageQueue.Msmq.UnitTests*|Grumpy.MessageQueue.TestTools.UnitTests*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 1266cac8-6dca-4462-9bb5-00bf387b791b
after_build:
  - ps: nuget pack Grumpy.MessageQueue.Nuget\bin\Release\Grumpy.MessageQueue.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: EqocuRN+dPLo43f6XC9SZIry4fYwoAibK7wTAte9Rrbc4Xl/OyWhGo75yv3/Rs+/
  skip_symbols: false
  artifact: /.*\.nupkg/
